language: go

go:
  - 1.8

before_install:
  - go get -u -v github.com/golang/dep/cmd/dep
  - go get -u -v github.com/gobuffalo/buffalo/buffalo
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash && source ~/.nvm/nvm.sh && nvm install 6 && nvm use 6
  - npm i -g npm5

install:
  - dep ensure -v
  - npm5 i

script:
  - buffalo test ./internal/...
  - buffalo build
